# Generated by Django 5.0.7 on 2024-07-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=100, verbose_name='Assunto')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=19, verbose_name='Telefone')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'db_table': 'contato',
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('arquivo', models.FileField(upload_to='core/static/cv', verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'Curriculum Vitae',
                'verbose_name_plural': 'Curriculum Vitae',
                'db_table': 'cv',
            },
        ),
        migrations.CreateModel(
            name='Experiencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100, verbose_name='Empresa')),
                ('logo', models.ImageField(upload_to='core/static/experiencias', verbose_name='Logo')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de fim')),
                ('stack', models.TextField(verbose_name='Stack')),
            ],
            options={
                'verbose_name': 'Experiência',
                'verbose_name_plural': 'Experiências',
                'db_table': 'experiencias',
            },
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidade', models.CharField(max_length=100, verbose_name='Habilidade')),
                ('icone', models.CharField(max_length=100, verbose_name='Ícone')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'db_table': 'habilidades',
            },
        ),
        migrations.CreateModel(
            name='ImagemIntroducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='core/static/introducao', verbose_name='Imagem')),
                ('alt', models.CharField(max_length=100, verbose_name='Texto alternativo')),
            ],
            options={
                'verbose_name': 'Imagem de introdução',
                'verbose_name_plural': 'Imagens de introdução',
                'db_table': 'imagem_introducao',
            },
        ),
        migrations.CreateModel(
            name='ImagemSobreMim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='core/static/sobre', verbose_name='Imagem')),
                ('alt', models.CharField(max_length=100, verbose_name='Texto alternativo')),
            ],
            options={
                'verbose_name': 'Imagem sobre mim',
                'verbose_name_plural': 'Imagens sobre mim',
                'db_table': 'imagem_sobre_mim',
            },
        ),
        migrations.CreateModel(
            name='Introducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Introdução',
                'verbose_name_plural': 'Introdução',
                'db_table': 'introducao',
            },
        ),
        migrations.CreateModel(
            name='RedesSociais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('icone', models.CharField(max_length=100, verbose_name='Ícone')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Rede social',
                'verbose_name_plural': 'Redes sociais',
                'db_table': 'redes_sociais',
            },
        ),
        migrations.CreateModel(
            name='SobreMim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Sobre mim',
                'verbose_name_plural': 'Sobre mim',
                'db_table': 'sobre_mim',
            },
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('imagem', models.ImageField(upload_to='core/static/projetos', verbose_name='Imagem')),
                ('alt', models.CharField(max_length=100, verbose_name='Texto alternativo')),
                ('repo', models.URLField(verbose_name='Repositório')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Site')),
                ('stack', models.ManyToManyField(related_name='projetos', to='sobre.habilidades', verbose_name='Stack')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'db_table': 'projetos',
            },
        ),
    ]
